version: '3.8'

services:
  telegram-quotes:
    build: ./quotes
    container_name: telegram-quotes-bot
    restart: unless-stopped
    #environment: # конфиги в .env только, в контейнере его нет
    #  - TG_Q_BOT_TOKEN=${TG_Q_BOT_TOKEN}
    #  - TG_Q_CHANNEL_ID=${TG_Q_CHANNEL_ID}
    #  - TG_Q_BASE_HOUR=${TG_Q_BASE_HOUR:-9}
    #  - TG_Q_BASE_MINUTE=${TG_Q_BASE_MINUTE:-0}
    #  - TG_Q_RANDOM_RANGE_MINUTES=${TG_Q_RANDOM_RANGE_MINUTES:-30}
    env_file:
      - ./quotes/.env  # Файл снаружи контейнера
    volumes:
      - ./quotes/data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"